/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_4;

import java.util.ArrayList;

/**
 *
 * @author CCSST
 */
public class TelaInicial extends javax.swing.JFrame {
    ArrayList<Afd> lista = new ArrayList<>();
    tela_tokens tokens = new tela_tokens();
    String entradaafd;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        entrada = new javax.swing.JTextArea();
        saida_token = new javax.swing.JLabel();
        erros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Tokens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Analisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        entrada.setColumns(20);
        entrada.setRows(5);
        jScrollPane1.setViewportView(entrada);

        saida_token.setBackground(new java.awt.Color(0, 0, 0));
        saida_token.setForeground(new java.awt.Color(255, 255, 0));
        saida_token.setText("jLabel1");
        saida_token.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        saida_token.setOpaque(true);

        erros.setBackground(new java.awt.Color(0, 0, 0));
        erros.setForeground(new java.awt.Color(255, 255, 0));
        erros.setText("jLabel2");
        erros.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        erros.setOpaque(true);

        jLabel1.setText("jLabel1");

        jLabel2.setText("Saída - Tokens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 464, Short.MAX_VALUE))
                            .addComponent(saida_token, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(saida_token, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(erros, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tokens.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        entradaafd = entrada.getText();
        lista = tokens.getListaAfd();
        //System.out.println("Lista: " + lista.size());

        //while(entradaafd != null){
            //System.out.println("Entrada: " + entradaafd);
            Analisar("q0");
            Analisar("q0");
            //Analisar();
        //}
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public String Analisar(String estado){
        Afd aux;
        String estado_atual = estado;
        String estado_final = null;
        char c;
        int cont = 0;
        int indice = 0;

        //for(int i = 0; i < lista.size(); i++){
            aux = lista.get(0);
            //System.out.println("Alfabeto: " + aux.alfabeto);
            while(cont < entradaafd.length()){
                //System.out.println("emtrou");
                c = entradaafd.charAt(cont);
                //System.out.println("estatual: " + c);
                if(transicao(aux.tableafd, aux.linhas, aux.colunas, aux.alfabeto, estado_atual, c)){
                    estado_atual = proximoEstado(aux.tableafd, aux.linhas, aux.colunas, aux.alfabeto, estado_atual, c);
                    //System.out.println("transicao");
                    if(estadoFinal(aux.tableafd, aux.linhas, aux.colunas, aux.alfabeto, estado_atual, c)){
                        //System.out.println("AQUI");
                        estado_final = estado_atual;
                        indice = 0;
                    }
                    else{
                        indice++;
                    }
                    cont++;
                    //System.out.println("cont: " + cont);
                }else
                    break;
            }
          
        //}
        //System.out.println("Estfinal: " + estado_final);
        if(estado_final != null){
            //System.out.println("entrou: " + indice);
            retrocederFita(indice);
            return aux.token;
        }
        return null;

    }
    
    boolean transicao(String[][]table, int li, int col, String alfa, String est_atual, char caracter){
        
        for(int i = 0; i < li; i++){
            for(int j = 1; j < col; j++){
                if(est_atual.equals(table[i][0]) || ("*"+est_atual).equals(table[i][0])){
                    if(alfa.charAt(j) == caracter){
                        //System.out.println("Entrou aqui satanas : " + "i: " + i + "j: " + j);
                        if(table[i][j].equals("")){
                            
                            return false;
                        }
                    }
                }
            }
        }
        
        return true;
    }
    
    String proximoEstado(String[][]table, int li, int col, String alfa, String est_atual, char caracter){
        //System.out.println("Col" + col);
        //System.out.println("est: " + est_atual);
        for(int i = 0; i < li; i++){
            for(int j = 1; j < col; j++){
                if(est_atual.equals(table[i][0]) || ("*" + est_atual).equals(table[i][0])){
                    //System.out.println("aqui");
                    if(alfa.charAt(j) == caracter){
                        return table[i][j];
                    }
                }
            }
        }
        return null;
    }
    
    boolean estadoFinal(String[][]table, int li, int col, String alfa, String est_atual, char caracter){
        
        for(int i = 0; i < li; i++){
            for(int j = 1; j < col-1; j++){
                //System.out.println("table: " + table[i][0]);
                if(("*" + est_atual).equals(table[i][0]))
                    return true;
            }
        }
        return false;
    }
    
    public void retrocederFita(int indice){
        entradaafd = entradaafd.substring(indice);
        System.out.println("Entrada" + entradaafd);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea entrada;
    private javax.swing.JLabel erros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel saida_token;
    // End of variables declaration//GEN-END:variables
}
