/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador_sintatico;

import java.util.ArrayList;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author CCSST
 */
public class Telatabela extends javax.swing.JFrame {
    int linha_length = 1;
    int coluna_length = 1;
    DefaultTableModel model;
    String[][] tabelinha;
    ArrayList <String> token=new ArrayList();
    ArrayList <String> variaveis =new ArrayList();
    
    
    
    
    /**
     * Creates new form Telatabela
     */
    public Telatabela() {
        initComponents();
        
       tabela.getTableHeader().setReorderingAllowed(false);
       //tabela.setAutoCreateColumnsFromModel(false);
       //tabela.getColumnModel().getColumn(tabela.getSelectedColumn()).setHeaderValue(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        linhamais = new javax.swing.JButton();
        linhamenos = new javax.swing.JButton();
        colunamais = new javax.swing.JButton();
        colunamenos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trabalho 6");
        setResizable(false);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label1.setText("Tabela Sintática");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Variáveis | Tokens"
            }
        ));
        tabela.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabela);

        jLabel1.setText("Nº Linhas: ");

        jLabel2.setText("Nº Colunas: ");

        linhamais.setText("+");
        linhamais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linhamaisActionPerformed(evt);
            }
        });

        linhamenos.setText("-");
        linhamenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linhamenosActionPerformed(evt);
            }
        });

        colunamais.setText("+");
        colunamais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colunamaisActionPerformed(evt);
            }
        });

        colunamenos.setText("-");
        colunamenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colunamenosActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(linhamais)
                                .addGap(3, 3, 3)
                                .addComponent(linhamenos)
                                .addGap(64, 64, 64)
                                .addComponent(jButton1)
                                .addGap(61, 61, 61)
                                .addComponent(colunamais)
                                .addGap(3, 3, 3)
                                .addComponent(colunamenos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addGap(224, 224, 224)
                                .addComponent(jLabel2)))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linhamais)
                    .addComponent(linhamenos)
                    .addComponent(colunamais)
                    .addComponent(colunamenos)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linhamaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linhamaisActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        Object[] linha = null;
        model.addRow(linha);
       linha_length++;
    }//GEN-LAST:event_linhamaisActionPerformed

    private void linhamenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linhamenosActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) tabela.getModel()).removeRow(tabela.getSelectedRow());
        linha_length--;
    }//GEN-LAST:event_linhamenosActionPerformed

    private void colunamaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colunamaisActionPerformed
        // TODO add your handling code here:
        String coluna = JOptionPane.showInputDialog("Nome da Coluna ");
        token.add(coluna);
        //Object[] col = null;
        ((DefaultTableModel) tabela.getModel()).addColumn(coluna);
        coluna_length++;
        
    }//GEN-LAST:event_colunamaisActionPerformed

    private void colunamenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colunamenosActionPerformed
        // TODO add your handling code here:
        int indice = tabela.getSelectedColumn();
        //tabela.removeColumn(tabela.getColumnModel().getColumn(indice));
        TableColumn coluna = (TableColumn) tabela.getColumnModel().getColumn(indice);
        token.remove(tabela.getColumnName(indice));
        tabela.removeColumn(coluna);
        tabela.revalidate();
        coluna_length--;
        //System.out.println("token"+token);
        
    }//GEN-LAST:event_colunamenosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        token.add("$");
        tabelinha = new String[linha_length][coluna_length];
        
        for(int i = 0; i< linha_length; i++){
            if(tabela.getValueAt(i,0)!=null)
                variaveis.add(tabela.getValueAt(i,0).toString());
            for(int j = 0; j< coluna_length; j++){
                if(tabela.getValueAt(i, j) == null)
                    tabelinha[i][j] = "";
                else
                    tabelinha[i][j] = tabela.getValueAt(i, j).toString();
            }
        }
        this.setVisible(false);
//        for(int i = 0; i< linha_length; i++){
//            for(int j = 0; j< coluna_length; j++){
//                System.out.print("tabelinha: " + tabelinha[i][j]+"  | ");
//            }
//            System.out.println("\n");
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public int getLinha_length() {
        return linha_length;
    }

    public int getColuna_length() {
        return coluna_length;
    }
    
    public ArrayList<String> getVariaveis() {
        return variaveis;
    }
    public String[][] getTabelinha() {
        return tabelinha;
    }

    public ArrayList<String> getToken() {
        return token;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telatabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colunamais;
    private javax.swing.JButton colunamenos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton linhamais;
    private javax.swing.JButton linhamenos;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
